[config]

[templates.waybar]
input_path = "~/.config/matugen/templates/waybar_matugen.css.tmpl"
output_path = "~/.config/waybar/matugen.css"
post_hook = "pkill -USR2 waybar || true"

[templates.wlogout]
input_path = "~/.config/matugen/templates/wlogout_matugen.css.tmpl"
output_path = "~/.config/wlogout/matugen.css"

[templates.kitty]
input_path = "~/.config/matugen/templates/kitty_colors.conf.tmpl"
output_path = "~/.config/kitty/colors.conf"
post_hook = "kitty @ set-colors -a ~/.config/kitty/colors.conf >/dev/null 2>&1 || true"

[templates.dunst]
input_path = "~/.config/matugen/templates/dunst_colors.conf.tmpl"
output_path = "~/.config/dunst/colors.conf"
post_hook = "command -v dunstctl >/dev/null 2>&1 && dunstctl reload || true"

[templates.swaylock]
input_path = "~/.config/matugen/templates/swaylock_config.tmpl"
output_path = "~/.config/swaylock/config"


